import { Story } from "./hn.js";

export function dayKey(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

export function rankLabel(index: number): string {
  const medals = ["🥇", "🥈", "🥉"];
  return medals[index] ?? `#${index + 1}`;
}

function storyLink(s: Story): string {
  if (s.url) return s.url;
  return `https://news.ycombinator.com/item?id=${s.id}`;
}

export function buildDigest(stories: Story[], date: Date): string {
  const head = `# Hacker News Daily Digest — ${dayKey(date)}

Generated by [hn-digest](https://github.com/Chrome-001/hn-digest).
Top ${stories.length} stories with a score of at least ${stories[0]?.score ?? 0}+,
ranked by points.

`;
  const rows = stories
    .map(
      (s, i) =>
        `${i + 1}. **${s.title}** — ${rankLabel(i)}\
        [${s.score} pts · ${s.descendants} comments]\
        (<${storyLink(s)}> | [discuss](https://news.ycombinator.com/item?id=${s.id}) · by ${s.by})`,
    )
    .join("\n");

  return `${head}## Today's top stories

${rows}
`;
}